// Константы, используемые в проекте

const FILMS_IN_LIST_COUNT = 5;
const TOP_RATED_AND_MOST_COMMENTED_FILM_COUNT = 2;
const MAX_DESCRIPTION_LENGTH = 140;
const EMOTIONS = ['smile', 'sleeping', 'puke', 'angry'];
const MIN_RATING_VALUE = 0;
const MAX_RATING_VALUE = 10;

export {FILMS_IN_LIST_COUNT, TOP_RATED_AND_MOST_COMMENTED_FILM_COUNT, MAX_DESCRIPTION_LENGTH, EMOTIONS, MIN_RATING_VALUE, MAX_RATING_VALUE};
